-- F EMMANUEL 85 VENTURES cloud database schema
-- Run this in Supabase SQL Editor before connecting the frontend.

do $$
begin
    create type public.app_role as enum ('manager', 'staff');
exception
    when duplicate_object then null;
end $$;

alter type public.app_role add value if not exists 'administrator';

do $$
begin
    create type public.transaction_type as enum ('cashIn', 'cashOut');
exception
    when duplicate_object then null;
end $$;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null check (char_length(trim(full_name)) >= 2),
    role public.app_role not null default 'staff',
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.customers (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) >= 2),
    next_of_kin text,
    phone text,
    created_at timestamptz not null default now()
);

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    date date not null,
    type public.transaction_type not null,
    pb_number integer not null check (pb_number > 0),
    customer_id bigint not null references public.customers(id),
    amount numeric(12, 2) not null check (amount > 0),
    staff_id uuid not null references public.profiles(id),
    received_by text,
    issued_by text,
    created_at timestamptz not null default now()
);

alter table public.transactions add column if not exists received_by text;
alter table public.transactions add column if not exists issued_by text;

create table if not exists public.audit_log (
    id bigint generated by default as identity primary key,
    actor_id uuid references public.profiles(id),
    action text not null,
    entity text not null,
    entity_id bigint,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists transactions_date_idx on public.transactions(date desc);
create index if not exists transactions_customer_idx on public.transactions(customer_id);
create index if not exists transactions_staff_idx on public.transactions(staff_id);

create or replace function public.current_role()
returns public.app_role
language sql stable security definer set search_path = public
as $$
    select role from public.profiles where id = auth.uid() and active = true;
$$;

create or replace function public.is_manager()
returns boolean
language sql stable security definer set search_path = public
as $$
    select public.current_role()::text in ('manager', 'administrator');
$$;

create or replace function public.prevent_role_escalation()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
    if not public.is_manager() and (new.role is distinct from old.role or new.active is distinct from old.active) then
        raise exception 'Only a manager can change roles or account status';
    end if;
    return new;
end;
$$;

drop trigger if exists profiles_role_guard on public.profiles;
create trigger profiles_role_guard before update on public.profiles
for each row execute function public.prevent_role_escalation();

alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.transactions enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists profiles_read_authenticated on public.profiles;
create policy profiles_read_authenticated on public.profiles for select to authenticated
using (active = true or id = auth.uid() or public.is_manager());
drop policy if exists profiles_manager_insert on public.profiles;
create policy profiles_manager_insert on public.profiles for insert to authenticated
with check (public.is_manager() and role = 'staff');
drop policy if exists profiles_manager_update on public.profiles;
create policy profiles_manager_update on public.profiles for update to authenticated
using (public.is_manager()) with check (public.is_manager());

drop policy if exists customers_manager_read on public.customers;
create policy customers_manager_read on public.customers for select to authenticated
using (exists (select 1 from public.profiles where id = auth.uid() and active = true));
drop policy if exists customers_manager_write on public.customers;
create policy customers_manager_write on public.customers for all to authenticated
using (public.is_manager()) with check (public.is_manager());

drop policy if exists transactions_authenticated_read on public.transactions;
create policy transactions_authenticated_read on public.transactions for select to authenticated
using (public.is_manager() or staff_id = auth.uid());
drop policy if exists transactions_staff_insert on public.transactions;
create policy transactions_staff_insert on public.transactions for insert to authenticated
with check (
    staff_id = auth.uid()
    and exists (select 1 from public.profiles where id = auth.uid() and active = true)
);
drop policy if exists transactions_manager_update on public.transactions;
create policy transactions_manager_update on public.transactions for update to authenticated
using (public.is_manager()) with check (public.is_manager());
drop policy if exists transactions_manager_delete on public.transactions;
create policy transactions_manager_delete on public.transactions for delete to authenticated
using (public.is_manager());

drop policy if exists audit_manager_read on public.audit_log;
create policy audit_manager_read on public.audit_log for select to authenticated
using (public.is_manager() or actor_id = auth.uid());
drop policy if exists audit_authenticated_insert on public.audit_log;
create policy audit_authenticated_insert on public.audit_log for insert to authenticated
with check (actor_id = auth.uid());

drop function if exists public.record_transaction(date, public.transaction_type, integer, bigint, numeric);
create or replace function public.record_transaction(
    p_date date,
    p_type public.transaction_type,
    p_pb_number integer,
    p_customer_id bigint,
    p_amount numeric,
    p_received_by text default null,
    p_issued_by text default null
)
returns public.transactions
language plpgsql security definer set search_path = public
as $$
declare
    result public.transactions;
    balance numeric;
begin
    if not exists (select 1 from public.profiles where id = auth.uid() and active = true) then
        raise exception 'Active staff account required';
    end if;
    if p_type = 'cashOut' then
        select coalesce(sum(case when type = 'cashIn' then amount else -amount end), 0)
        into balance from public.transactions where customer_id = p_customer_id;
        if balance < p_amount then raise exception 'Insufficient customer balance'; end if;
    end if;
    insert into public.transactions(date, type, pb_number, customer_id, amount, staff_id, received_by, issued_by)
    values (p_date, p_type, p_pb_number, p_customer_id, p_amount, auth.uid(), p_received_by, p_issued_by)
    returning * into result;
    insert into public.audit_log(actor_id, action, entity, entity_id)
    values (auth.uid(), 'create', 'transaction', result.id);
    return result;
end;
$$;

grant execute on function public.record_transaction(date, public.transaction_type, integer, bigint, numeric, text, text) to authenticated;

create or replace function public.update_transaction(
    p_id bigint,
    p_date date,
    p_pb_number integer,
    p_customer_id bigint,
    p_amount numeric,
    p_received_by text default null,
    p_issued_by text default null
)
returns public.transactions
language plpgsql security definer set search_path = public
as $$
declare
    existing public.transactions;
    result public.transactions;
    balance numeric;
begin
    if not public.is_manager() then raise exception 'Manager access required'; end if;
    select * into existing from public.transactions where id = p_id for update;
    if not found then raise exception 'Transaction not found'; end if;
    if p_amount <= 0 or p_pb_number <= 0 then raise exception 'Invalid transaction values'; end if;
    if existing.type = 'cashOut' then
        select coalesce(sum(case when type = 'cashIn' then amount else -amount end), 0)
        into balance from public.transactions
        where customer_id = p_customer_id and id <> p_id;
        if balance < p_amount then raise exception 'Insufficient customer balance'; end if;
    end if;
    update public.transactions
    set date = p_date, pb_number = p_pb_number, customer_id = p_customer_id,
        amount = p_amount, received_by = p_received_by, issued_by = p_issued_by
    where id = p_id
    returning * into result;
    insert into public.audit_log(actor_id, action, entity, entity_id)
    values (auth.uid(), 'update', 'transaction', result.id);
    return result;
end;
$$;

grant execute on function public.update_transaction(bigint, date, integer, bigint, numeric, text, text) to authenticated;

create or replace function public.setup_first_manager(p_full_name text)
returns public.profiles
language plpgsql security definer set search_path = public
as $$
declare
    result public.profiles;
begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;
    perform pg_advisory_xact_lock(hashtext('susu_first_manager_setup'));
    if exists (select 1 from public.profiles where role::text in ('manager', 'administrator')) then raise exception 'A manager already exists'; end if;
    if char_length(trim(p_full_name)) < 2 then raise exception 'A valid full name is required'; end if;
    insert into public.profiles(id, full_name, role, active)
    values (auth.uid(), trim(p_full_name), 'manager', true)
    returning * into result;
    return result;
end;
$$;

grant execute on function public.setup_first_manager(text) to authenticated;

-- First manager setup is intentionally performed through Supabase Auth plus a protected setup flow.
-- Do not make the first user a manager from an untrusted client in production.
